version: "3.9"

services:
  railway-app:
    container_name: railway-reservation-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped
    command: npm start
